overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  nodemailer@<7.0.11: '>=7.0.11'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<=7.0.10: '>=7.0.11'
  qs@<6.14.1: '>=6.14.1'
  tmp@<=0.2.3: '>=0.2.4'
